CREATE USER 'ejecutor'@'localhost' IDENTIFIED BY 'YeKu7A';
GRANT USAGE ON *.* TO 'ejecutor'@'localhost';
GRANT SELECT  ON TABLE `bd_numeracion`.`tb_gamers_win` TO 'ejecutor'@'localhost';
GRANT SELECT  ON TABLE `bd_numeracion`.`tb_log` TO 'ejecutor'@'localhost';
GRANT SELECT  ON TABLE `bd_numeracion`.`tb_microwisp` TO 'ejecutor'@'localhost';
GRANT SELECT  ON TABLE `bd_numeracion`.`tb_numeracion_win` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON FUNCTION `bd_numeracion`.`fun_get_last_connection` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON FUNCTION `bd_numeracion`.`fun_get_last_modified` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_cr_last_connection` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`dnitocodcl` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_get_client_info` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_get_last_update` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_read_num` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_validate_gamer` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_init_ticket` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_uptatention_ticket` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_close_ticket` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_register_idxdoc` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_get_discordid_doc` TO 'ejecutor'@'localhost';
GRANT EXECUTE  ON PROCEDURE `bd_numeracion`.`sp_update_discordID_doc` TO 'ejecutor'@'localhost';
FLUSH PRIVILEGES;
CREATE USER 'cargador'@'localhost' IDENTIFIED BY '123456789';
GRANT USAGE ON *.* TO 'cargador'@'localhost';
GRANT SELECT, INSERT  ON TABLE `bd_numeracion`.`tb_log` TO 'cargador'@'localhost';
GRANT SELECT, DELETE, INSERT  ON TABLE `bd_numeracion`.`tb_microwisp` TO 'cargador'@'localhost';
GRANT SELECT, DELETE, INSERT  ON TABLE `bd_numeracion`.`tb_numeracion_win` TO 'cargador'@'localhost';
GRANT SELECT, DELETE, INSERT  ON TABLE `bd_numeracion`.`tb_gamers_win` TO 'cargador'@'localhost';
GRANT EXECUTE  ON FUNCTION `bd_numeracion`.`fun_get_last_modified` TO 'cargador'@'localhost';
FLUSH PRIVILEGES;